#ifndef GRAPHVEX_TYPE_H
#define GRAPHVEX_TYPE_H

#include "oop/type.h"

// graphvex/type.h — the graphvex project's type registry.
//
// OWNERSHIP: every graphvex class ID lives here, not in vexspoke's
// oop/type.h. Included by graphvex sources that stamp headers with
// graphvex-owned types (font atlases today; texture/vfs classes next).
//
// UNIFORM PER-PROJECT NUMBERING (uniform type rule): each project's
// registry numbers its own classes starting at 1; the project byte in the
// 64-bit type id disambiguates every repo's id #1. graphvex id #1
// (ID_FONT) is distinct from vexspoke id #1 (ID_INT) and darling id #1
// (ID_PANEL) because the PROJ_* byte differs. Full TYPE_*_SINGLETON ids
// carry PROJ_GRAPHVEX and must be used at runtime dispatch; bare ID_*
// constants name vexspoke's own class space only. New graphvex classes
// take the next free number below — never invent an out-of-registry
// window (Rule 6: the collision that id space causes is a defect).

// --- GRAPHVEX GPU OBJECTS (numbered 1..N, uniform per-project) ---
#define ID_FONT	1u
#define ID_IMAGE	2u
#define ID_SWAPCHAIN	3u
#define ID_SEMAPHORE	4u
#define ID_FENCE	5u
#define ID_COMMAND_BUFFER	6u
#define ID_COMMAND_QUEUE	7u
#define ID_GPU_BUFFER	8u
#define ID_BINDLESS_HEAP	9u
#define ID_SHAPE	10u
#define ID_MESH	11u
#define ID_MESHLET	12u
#define ID_SCENE	13u
#define ID_STROKE	14u
#define ID_BRUSH	15u
#define ID_VECTOR_BRUSH	16u
#define ID_RASTER_BRUSH	17u
#define ID_DRAWABLE	18u
#define ID_LAYERED_DRAWABLE	19u
#define ID_VECTOR_DRAWABLE	20u
#define ID_LAYERED_VECTOR_DRAWABLE	21u
#define ID_PIPELINE	22u
#define ID_PASS	23u
#define ID_FRAME_IMPORTER	24u

#define TYPE_FONT_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_FONT)
#define TYPE_IMAGE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_IMAGE)
#define TYPE_SWAPCHAIN_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_SWAPCHAIN)
#define TYPE_SEMAPHORE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_SEMAPHORE)
#define TYPE_FENCE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_FENCE)
#define TYPE_COMMAND_BUFFER_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_COMMAND_BUFFER)
#define TYPE_COMMAND_QUEUE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_COMMAND_QUEUE)
#define TYPE_GPU_BUFFER_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_GPU_BUFFER)
#define TYPE_BINDLESS_HEAP_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_BINDLESS_HEAP)
#define TYPE_SHAPE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_SHAPE)
#define TYPE_MESH_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_MESH)
#define TYPE_MESHLET_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_MESHLET)
#define TYPE_SCENE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_SCENE)
#define TYPE_STROKE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_STROKE)
#define TYPE_BRUSH_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_BRUSH)
#define TYPE_VECTOR_BRUSH_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_VECTOR_BRUSH)
#define TYPE_RASTER_BRUSH_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_RASTER_BRUSH)
#define TYPE_DRAWABLE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_DRAWABLE)
#define TYPE_LAYERED_DRAWABLE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_LAYERED_DRAWABLE)
#define TYPE_VECTOR_DRAWABLE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_VECTOR_DRAWABLE)
#define TYPE_LAYERED_VECTOR_DRAWABLE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_LAYERED_VECTOR_DRAWABLE)
#define TYPE_PIPELINE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_PIPELINE)
#define TYPE_PASS_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_PASS)
#define TYPE_FRAME_IMPORTER_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_FRAME_IMPORTER)

#endif